version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mgsisk"
    labels:
      - "change"
    reviewers:
      - "mgsisk"
