language: node_js

node_js:
  - node

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        - provider: releases
          api_key:
            secure: tMMfnGEJh9m8+vUtn+rqw1Z9pemM+rI8RJeaYuhbDAOpgTldQOlcTqkfuELCHuyJ58AgXoZRaw0hgwG5MWqT+wSKWoLdac94x91ZWRSaSKfQsuGP4yvOuUInTTaH0XRbSVQzNk/nh1bpLVjU3xgqpyQWyBeQTV28pnK5/n9sz+twiNZBDecUBvIVNiyuSEiutok/MWFnlEuADft+JsDTuwLjQWnYGiU9LmADGis4D7uHAAMl2cCYWNCh+8vsspyQJz8mY+cXYbXz9Uvb8isUx/pTB35hRw5LJmoDPqR1qS2hZjuIqdZC0ekpkljcfmvOxEI4ekTAJYiQR4jHrB64Almz7Y9Ro1pDEQOs9dIXwV7/NKR8rsfZaxodV/GEchIEzgLGIksVwaI7W5GXer+t1V8BXehVvVAvmh9wx0uOOzTNC+y2y2dayRc7QrZTrDHUiUmp4prlwow4We1pTWs2L2pvtCXOODq1JS8JotYpX2fbAk6csvcYQsjGaXQaA9HxMDSjn/tkFNiFea36wI0HPs+SvH9Dc/rX3fksdR1FOTQa8IpOkWgO1z7qJg4wjTR66M0rCPj2Wh3eQot3y/nnQXyk1A5iBu8W4HWg7fo1LW3QyxaKp0CVmctTUJ3kcRrXpuFgBn54EZST9IBohKjWM4nJ3lLnhh63dU0qdKuBCaY=
          on:
            repo: mgsisk/mgsisk
            tags: true
